os: osx

language: node_js
node_js:
- '11'

cache:
  directories:
  - "./node_modules"

before_script:
- npm install -g gulp-cli
- npm install

script: gulp build

env:
  secure: F0BUej5xaTZS3zcoNLadGwGugnDfEY5hgbOWUegZ+403mR4K6FcWOk1NIf3ICy7WbDLvb1yi3bylvuVQspfXu8rCjiMP8y1SIZnqvqgihnU4OHinq6RCCz1cN2Q6NaKygtzdL0KRH4BODwAA3+6Kya/i1P27xG0uRUhgCBbE/gs8tVtQKmkjeHEMlHfidb0+IKba33pZTQfUt5Gy2gL/TlFB8ay4nhADFYVYwcqvX0DqmU2h7ZnUSJ8j1/RsxngrIzQTyMw/VcQkcFKsERo0xJ0DsYivDUnM+5sPOwiXEPmT2X89FxQxlwHiuZww9BNBj1FKhjkV9UQbH6H4KdE4aavsVNmCn04jKEd8nph1M8uTkXCA79xMYKAEMe2uYp+kes2dtyS+ojL335ccGYG5u2ZAI1O6DB2B7v8YBV0hTsGHkynwxlZy+os4Ij7D9uSRASfS882ddkvZ7GvhPrUQ92ZLVQvxikS17J520enpC/ChjrqwzvPC91Oi0B2luaS/G6tK6+SZJXHIJlbyoTzpuv4HfLdl1irizKF+6dWNZXdaB12qjb2MAOnSc7eljGsGkaYa0T5Qg9nWsZp8Syy4qRdUGwLg5RBgfQ0gyDEF6f3kuOOlvcZEJq2bVlC5XtezMYRyC65k5IY5GEOLdWzfLmEd/a+RpeUcSdAOCZO4rW8=
after_success:
- curl --ftp-create-dirs -T "{404.php,footer.php,front-page.php,functions.php,header.php,index.php,page.php,style.css,static,inc}" sftp://${SFTP_USER}:${SFTP_PASSWORD}@scoutingoost1.nl/subdomains/dev/wp-content/themes/scoutingoost1
